hw2
apushkarou/react-20230914 pull request #1
Opened 2023-09-28 00:14 UTC by apushkarou

2023-09-28 15:45 UTC, SArchieEdu requested changes

2023-09-28 15:45 UTC, SArchieEdu commented on src/pages/Main/component.jsx
> +  const [activeRestaurant, setActiveRestaurant] = useState(restaurants[0]);
хуки нельзя вызывать условно

2023-09-28 15:45 UTC, SArchieEdu commented on src/pages/Main/component.jsx
> +      <Restaurant restaurantData={activeRestaurant} />
можно заменить restaurantData на restaurant, тк любой проп data, смысла не добавляет, только раздывает имя. Аналогично и Info, Details и тд

2023-09-28 15:45 UTC, SArchieEdu commented on src/components/Reviews/component.jsx
> +const ReviewItem = ({ user, text, rating }) => {
нет, лучше отдельный компонент. Это раздувает базовый компонент, не дает переиспользовать маленький компоеннт.
Имя ReviewItem лучше заменить на Review, тк сейчас только имя привязывает этот компонент к списку и не дает переиспользовать в будущем

2023-09-28 15:45 UTC, SArchieEdu commented on src/components/MenuItem/component.jsx
> +export const MenuItem = ({ product }) => {
аналогично с именем

2023-09-28 15:58 UTC, apushkarou commented on src/pages/Main/component.jsx
> +  const [activeRestaurant, setActiveRestaurant] = useState(restaurants[0]);
@SArchieEdu  немного не понял, а в чем здесь "условно". Мы же просто записываем в activeRestaurant первый ресторан

2023-10-02 09:04 UTC, SArchieEdu commented on src/pages/Main/component.jsx
> +  const [activeRestaurant, setActiveRestaurant] = useState(restaurants[0]);
выше есть ранний ретерн

2023-10-02 09:05 UTC, SArchieEdu approved these changes
Нужно поправить условный вызов хука и потом можно мерджить

2023-10-02 18:48 UTC, merged